## Introduction

In this tutorial, we will cover:

* Basic Python: Basic data types (Containers, Lists, Dictionaries, Sets, Tuples), Functions, Classes
* Numpy: Arrays, Array indexing, Datatypes, Array math, Broadcasting
* Matplotlib: Plotting, Subplots, Images


In [ ]:
!python --version

## Basics of Python

Python is a high-level, dynamically typed multiparadigm programming language. Python code is often said to be almost like pseudocode, since it allows you to express very powerful ideas in very few lines of code while being very readable. As an example, here is an implementation of the classic quicksort algorithm in Python:

### Basic data types

#### Numbers

Integers and floats work as you would expect from other languages:

In [ ]:
#numeric --> Integer,Flaot ,Boolean 

In [ ]:
#variables are named memory locations

In [1]:
x = 3
print(x, type(x))

3 <class 'int'>


In [ ]:
id(x)

In [ ]:
x =5

In [ ]:
id(x)

x<-- 2844942887344 = 5

In [ ]:
#variables are named memory locations

In [ ]:
print(x + 1)   # Addition
print(x - 1)   # Subtraction
print(x * 2)   # Multiplication
print(x ** 2)  # Exponentiation

In [ ]:
pow(2,3) # 2**3

In [ ]:
x

In [ ]:
x = x+1

In [ ]:
id(x)

In [ ]:
x

In [ ]:
x += 1 # x = x+1

In [ ]:
x

In [ ]:
x += 1 # x = x+1
print(x)
x *= 2 # x = x*2
print(x)

In [ ]:
y = 2.5
print(type(y))
print(y, y + 1, y * 2, y ** 2)

Note that unlike many languages, Python does not have unary increment (x++) or decrement (x--) operators.

Python also has built-in types for long integers and complex numbers; you can find all of the details in the [documentation](https://docs.python.org/3.7/library/stdtypes.html#numeric-types-int-float-long-complex).

#### Booleans

Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols (`&&`, `||`, etc.):

In [ ]:
t = True
f = False

In [ ]:
t, f = True, False #any non zero -->True
print(type(t))

In [ ]:
x = 5
y = 6

In [ ]:
x,y = 5,6 #unpacking

In [ ]:
x

Now we let's look at the operations:

In [ ]:
print(t and f) # Logical AND;
print(t or f)  # Logical OR;
print(not t)   # Logical NOT;
print(t != f)  # Logical XOR;

In [ ]:
#MSD  --> 

In [ ]:
#Mutibility --> a data type whose value can be changed is called muttable

#LSD -- > mutable data types

#### Strings

In [ ]:
a = "Harsh"

In [ ]:
type(a)

In [ ]:
a[-4]

In [ ]:
b = "Sukla"

In [ ]:
a + b

In [ ]:
a + " "+ b #string concatenation

In [ ]:
a = "Pragyan"

In [ ]:
len(a)

In [ ]:
len??

In [ ]:
2**3

In [ ]:
pow(2,3)

In [ ]:
pow??

In [ ]:
hello = 'hi'   # String literals can use single quotes
world = "Pragyan"   # or double quotes; it does not matter
print(hello, len(hello))

In [ ]:
id(hello)

In [ ]:
harsh = hello + ' ' + world  # String concatenation
print(harsh)

In [ ]:
hello

In [ ]:
world

In [ ]:
name = "Rajnish"

In [ ]:
print(f"My name is {name} ")

In [ ]:
print(f"My name is {name} ,I am 27 years old ")

In [ ]:
print("My name is {} , I love {}!!".format("Mahesh","Pizza"))

In [ ]:
marks = 75

In [ ]:
company = 'Infosys'

In [ ]:
print(f'I will get {marks} in final semester and get a job at {company}') #fstring

In [ ]:
print('I will get {} in final semester and get a job at {}'.format(marks,company))

In [ ]:
hello

In [ ]:
hw12 = '{} {} {}'.format(hello, 34, "Pragyan")  # string formatting
print(hw12)

In [ ]:
name = "Pragyan"

In [ ]:
print(f'{name}') #fstring

In [ ]:
marks = 95
print(f'I got {marks}')

In [ ]:
a = input("Enter something : ") #Input function converts all data types to string

In [ ]:
a

In [ ]:
type(a)

In [ ]:
a = int(input("Enter something : "))

In [ ]:
a

In [ ]:
type(a)

In [ ]:
a = eval(input("Enter something : ")) # generalised 

In [ ]:
a

In [ ]:
type(a)

In [ ]:
name = "DurgaRao Raja"

In [ ]:
len(name)

In [ ]:
name[1]

In [ ]:
name[-1]

String objects have a bunch of useful methods; for example:

In [ ]:
s = "durgarao" # strings are immutable objects
print(s.capitalize())  # Capitalize a string
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
#print(s.rjust(7))      # Right-justify a string, padding with spaces
#print(s.center(7))     # Center a string, padding with spaces
print(s.replace('u', 'k'))  # Replace all instances of one substring with another
print('  world '.strip())  # Strip leading and trailing whitespace

In [ ]:
s.upper??

In [ ]:
help(s.capitalize)

In [ ]:
s.capitalize??

In [ ]:
#docstings are description of a function

In [ ]:
def add(a,b):
    """
    It takes two inputs ,adds them and returns the sum 
    """
    return a+b

In [ ]:
add??

In [ ]:
s

In [ ]:
s1 =s.upper()

In [ ]:
s1

In [ ]:
type(s1)

In [ ]:
isinstance??

You can find a list of all string methods in the [documentation](https://docs.python.org/3.7/library/stdtypes.html#string-methods).

In [ ]:
isinstance(1,int)

In [3]:
isinstance("ABC",str)

True

In [ ]:
isinstance(True,bool)

In [ ]:
isinstance(False,bool)

In [ ]:
isinstance(False,int) #False is 0,True is any non zero

In [ ]:
isinstance(True,int)

In [ ]:
None

### Containers

Python includes several built-in container types: lists, dictionaries, sets, and tuples.

In [ ]:
ls = ["Allo","tomato",100,False,["Rasgullu","Kalakand","ladoo"]] # it is a collection of heterogeneous elements

In [ ]:
ls

In [ ]:
len(ls)

In [ ]:
ls

In [ ]:
ls[0]  = "Chicken" #lists are mutable

In [ ]:
name = "Harsh"

In [ ]:
name[0] = 'P'

In [ ]:
ls 

In [ ]:
ls.append("Salt")

In [ ]:
ls.remove("Salt")

In [ ]:
ls

In [ ]:
ls.remove("tomato")

In [ ]:
ls

In [ ]:
del ls[0]

In [ ]:
ls.remove??

In [ ]:
ls[-1]

In [ ]:
ls[-2]

In [ ]:
ls[4]

In [ ]:
ls[4][2]

In [ ]:
ls[-1]

In [ ]:
ls[2]

In [ ]:
ls[3]

In [ ]:
ls[4]

In [ ]:
my_list1 = [None,None,None]

In [ ]:
my_list1

In [ ]:
my_list1[0] = 'tamatar'

In [ ]:
my_list1

In [ ]:
my_list = [None]*5

In [ ]:
my_list 

In [ ]:
ls1 = [1,2,3]*4

In [ ]:
ls1

#### Lists

A list is the Python equivalent of an array, but is resizeable and can contain elements of different types:

In [ ]:
xs = [8, 9, 10]   # Create a list
print(xs, xs[2])
print(xs[-1])     # Negative indices count from the end of the list; prints "2"

In [ ]:
xs[2]

In [ ]:
xs[2] = 'foo'    # Lists can contain elements of different types,also lists are mutable
print(xs)

In [ ]:
xs[2]

In [ ]:
xs.append('bar') # Add a new element to the end of the list
print(xs)  

In [ ]:
x = xs.pop()     # Remove and return the last element of the list
print(x, xs)

In [ ]:
num1 = [1,2,3,4,5]

In [ ]:
num1

In [ ]:
list(range(5,31,3))

In [ ]:
list(range(30,1,-3))

In [ ]:
num = list(range(9,25))

In [ ]:
num

In [ ]:
num[3:]

In [ ]:
num[0:3] #--> 0 to 2

In [ ]:
num[1:3] #--> # index 1 and 2

In [ ]:
range(start,end,step)

In [ ]:
list(range(1,10,2))

In [ ]:
list(range(0,5))

In [ ]:
nums = list(range(5))    # range is a built-in function that creates a list of integers


In [ ]:
nums

In [ ]:

print(nums[2:4])    # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
 

In [ ]:
print(nums[2:])

## EDA

In [ ]:
num = list(range(1,25,3))

In [ ]:
num

In [ ]:
list(range(50,-1,-3))

As usual, you can find all the gory details about lists in the [documentation](https://docs.python.org/3.7/tutorial/datastructures.html#more-on-lists).

#### Slicing

In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing:

In [ ]:
nums = list(range(7,18))    # range is a built-in function that creates a list of integers
print(nums)         # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])    # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])     # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])     # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])      # Get a slice of the whole list; prints ["0, 1, 2, 3, 4]"
print(nums[:-1])    # Slice indices can be negative; prints ["0, 1, 2, 3]"
nums[2:4] = [8, 9] # Assign a new sublist to a slice
print(nums)         # Prints "[0, 1, 8, 9, 4]"

In [ ]:
nums[-2]

#### Loops

You can loop over the elements of a list like this:

In [ ]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)

In [ ]:
animals[2]

In [ ]:
len(animals)

In [ ]:
list(range(0,len(animals)))

In [ ]:
for i in range(0,len(animals)):
    print(animals[i])

In [ ]:
animals

In [ ]:
for i in [0, 1, 2]:
    print(i)
    print(animals[i])

In [ ]:
list(enumerate(animals))

In [ ]:
for index, value in enumerate(animals):
    print(index)
    print(value)
    print("************")

If you want access to the index of each element within the body of a loop, use the built-in `enumerate` function:

In [ ]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print('#{}: {}'.format(idx + 1, animal))

#### List comprehensions:

When programming, frequently we want to transform one type of data into another. As a simple example, consider the following code that computes square numbers:

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)

You can make this code simpler using a list comprehension:

In [ ]:
[x**2 for x in nums]
    

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)

List comprehensions can also contain conditions:

In [ ]:
[x**2 for x in nums  if x%2 ==0]
  

In [ ]:
nums = [1, 2, 3, 4,5]
even_squares = [x ** 2 for x in nums if x % 2== 0]
print(even_squares)

In [ ]:
nums = list(range(1,100))
odd_squares = [x ** 2 for x in nums if x % 2!= 0]
print(odd_squares)

In [ ]:
10/3

In [ ]:
a = 0.1 + 0.1 + 0.1

In [ ]:
a

In [ ]:
b = 0.3

In [ ]:
a

In [ ]:
b 

In [ ]:
4 == 6

In [ ]:
a == b # ==  is used for value comparision

In [ ]:
id(a)

In [ ]:
id(b)

In [ ]:
a is b #is is used for address comparision 

In [ ]:
x =10

In [ ]:
y = 10

In [ ]:
id(x)

In [ ]:
id(y)

In [ ]:
x == y

In [ ]:
x is y

In [ ]:
p = -6

In [ ]:
q = -6

In [ ]:
id(p)

In [ ]:
id(q)

In [ ]:
p is q

In [ ]:
p == q

In [ ]:
x = 256

In [ ]:
y =256

In [ ]:
x is y

In [ ]:
id(x)

In [ ]:
id(y)

In [ ]:
x = 257

In [ ]:
y = 257

In [ ]:
id(x)

In [ ]:
id(y)

In [ ]:
x == y

In [ ]:
nums = [0,1,2,3,4]

In [ ]:
nums*3

In [ ]:
l1 = [1,2,3]

In [ ]:
l2 = [4,6,3]

In [ ]:
l1.extend(l2)

In [ ]:
l1

In [ ]:
l3 = [*l2,*l1] #unpacking

In [ ]:
l3

In [ ]:
list(range(0,10))

In [ ]:
import numpy as np # numerical python

In [ ]:
nums = [1,2,3,5]

In [ ]:
arr = np.array(nums) # array contains similar elements 

In [ ]:
arr

In [ ]:
arr*3  #vectorization

#### Dictionaries

A dictionary stores (key, value) pairs, similar to a `Map` in Java or an object in Javascript. You can use it like this:

In [ ]:
d1 = {'Rollno': 2 ,"Name": 'Rajnish','email':'h.s@gmail.com'}

In [ ]:
d1['Rollno']

In [ ]:
d1['Name']

In [ ]:
d1['email']

In [ ]:
print(d1)

In [ ]:
d1.keys()

In [ ]:
d1.values()

In [ ]:
d1.items()

In [ ]:
d1.get("Rollno")

In [ ]:
d1['Rollno']

In [ ]:
d1.get("address")

In [ ]:
d1['address']

In [ ]:
d1.get('address',"Key not found")

In [ ]:
d1

In [ ]:
d1.update({'ph':9900214662})

In [ ]:
d1

In [ ]:
d1['city'] = 'Patna'

In [ ]:
d1

In [ ]:
d1['city'] = "kanpur"

In [ ]:
d1

In [ ]:
d1.update({'ph':87665578778667})

In [ ]:
d1

In [ ]:
del d1['ph']

In [ ]:
d1

In [ ]:
for k in d1.keys():
    print(k)

In [ ]:
for v in d1.values():
    print(v)

In [ ]:
for k,v in d1.items():
    print(k)
    print(v)
    print("###############")

In [ ]:
d1.keys()

In [ ]:
'city' in d1

In [ ]:
'address' in d1

In [ ]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['cat'])       # Get an entry from a dictionary; prints "cute"
print('cat' in d)     # Check if a dictionary has a given key; prints "True"

In [ ]:
"pragyan" in d

In [ ]:
d['fish'] = 'wet'    # Set an entry in a dictionary
print(d['fish'])      # Prints "wet"

In [ ]:
d

In [ ]:
print(d['monkey'])  # KeyError: 'monkey' not a key of d

In [ ]:
d['fish']

In [ ]:
d.get('fish')

In [ ]:
d.get('monkey')

In [ ]:
d.get('Pragyan','Not Present')

In [ ]:
d.get('Pragyan')

In [ ]:
d['Pragyan']

In [ ]:
print(d.get('monkey', 'Not present'))  # Get an element with a default; prints "N/A"
print(d.get('fish', 'N/A'))    # Get an element with a default; prints "wet"

In [ ]:
del d['fish']        # Remove an element from a dictionary
print(d.get('fish', 'Deleted')) # "fish" is no longer a key; prints "N/A"

In [ ]:
d

You can find all you need to know about dictionaries in the [documentation](https://docs.python.org/2/library/stdtypes.html#dict).

It is easy to iterate over the keys in a dictionary:

In [ ]:
d

In [ ]:
d.keys()

In [ ]:
d.values()

In [ ]:
d.items()

In [ ]:
for key in d.keys():
    print(key)

In [ ]:
for value in d.values():
    print(value)

In [ ]:
d = {"a":1,"b":2}

In [ ]:
d.items()

In [ ]:
for k,v in d.items():
    print(k)
    print(v)
    print("*****")

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
    print('A {} has {} legs'.format(animal, legs))

Dictionary comprehensions: These are similar to list comprehensions, but allow you to easily construct dictionaries. For example:

In [ ]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = { x: x ** 2 for x in nums if x % 2 == 0 }
print(even_num_to_square)

#### Sets

A set is an unordered collection of distinct elements. As a simple example, consider the following:

In [ ]:
animals = {'cat', 'dog'}
print('cat' in animals)   # Check if an element is in a set; prints "True"
print('fish' in animals)  # prints "False"

In [ ]:
animals.add('fish')      # Add an element to a set
print('fish' in animals)
print(len(animals))       # Number of elements in a set;

In [ ]:
animals.add('cat')       # Adding an element that is already in the set does nothing
print(len(animals))       
animals.remove('cat')    # Remove an element from a set
print(len(animals))       

_Loops_: Iterating over a set has the same syntax as iterating over a list; however since sets are unordered, you cannot make assumptions about the order in which you visit the elements of the set:

In [ ]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('#{}: {}'.format(idx + 1, animal))

Set comprehensions: Like lists and dictionaries, we can easily construct sets using set comprehensions:

In [ ]:
from math import sqrt
print({int(sqrt(x)) for x in range(30)})

#### Tuples

A tuple is an (immutable) ordered list of values. A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot. Here is a trivial example:

In [ ]:
d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys


In [ ]:
d

In [ ]:
a = (1,2,4,5,6)

In [ ]:
type(a)

In [ ]:
s1 = "Pragyan?"

In [ ]:
s1[0] = "R"

In [ ]:
a[1] = 8

In [ ]:
d = {"a": 1, "b":2}

In [ ]:
d[1] = "b"

In [ ]:
d

In [13]:
b = (1,)

In [14]:
type(b)

tuple

In [6]:
b = 1,

In [7]:
type(b)

tuple

In [8]:
b

(1,)

In [1]:
c = ()

In [5]:
type(c)

tuple

In [4]:
c = tuple()

In [ ]:
t = (5, 6)       # Create a tuple
print(type(t))
print(d[t])       
print(d[(1, 2)])

In [ ]:
t[0] = 1

In [ ]:
t1 = (1,2,"abc",2.4,[5,6,7])

In [ ]:
t1[4][0] = 8

In [ ]:
t1[4][0]=9

In [ ]:
t1

In [ ]:
def add(a,b,c=0):
    print(a,b,c)
    return a+b+c

In [ ]:
add(1,2)#arguments

In [ ]:
add(1,2,3)

In [ ]:
t = (1,3,4,5,7)

In [ ]:
sum(t)

In [ ]:
def add(*args):
    print(args)
    print(type(args))
    
    return sum(args)

In [ ]:
add(1,2)

In [ ]:
add(1,2,34,8)

In [ ]:
add(1,2,34,5,67,9)

In [ ]:
def add(a,b):
    print(a,b)
    return a+b

In [ ]:
add(1,2)

In [ ]:
add(b=3,a=1)#keyword arguments

In [ ]:
#define a function
def add(a,b):#here a,b are functional parameters
    """
    It adds takes two elements as input ,adds them and return the sum 
    """
    return a+b

In [ ]:
#call the function
add(2,3)#2 and 3 are called arguments

In [ ]:
add(b =5, a = 4)#keyword arguments

In [ ]:
add(a=1,b= 2,3)

In [ ]:
def add(a,b,c=0):#here c is having a default value
    """
    It takes two inputs ,adds them and returns the sum
    """
    return a+b+c

In [ ]:
add(1,2,4)

In [ ]:
add(1,2)#positional

In [ ]:
add(b = 3,a =6)#keyword

In [ ]:
t = (1,2,3,4,5,6)

In [ ]:
sum(t)

In [ ]:
def add(*args):
    print(type(args))
    print(args)
    return sum(args)

In [ ]:
add(1,2)

In [ ]:
add(1,2,3,5,7)

In [ ]:
d = {'a':1,'b':2,'c':3}

In [ ]:
d.keys()

In [ ]:
d.items()

In [ ]:
d.values()

In [ ]:
sum(d.values())

In [ ]:
def add_k(**kwargs):
    print(kwargs)
    print(type(kwargs))
    
    return sum(kwargs.values())
    
    

In [ ]:
add_k(a=1,c =2,d =3)

In [ ]:
def add_g(*args,**kwargs):
    print(*args)
    print(kwargs)
    
    return sum(args) + sum(kwargs.values())
    

In [ ]:
add_g(1,2,3,a=8,b=9)

In [ ]:
add_g(a=3,b=6,c=2,1,2)

In [ ]:
students = ['Ajay','Rajat','Sapna','Priyanka','Sauya']

In [ ]:
students[1]

In [ ]:
for s in students:
    print(s.upper())

In [ ]:
list(range(0,len(students)))

In [ ]:
for s in range(0,len(students)):
    print(students[s].upper())

In [ ]:
list(enumerate(students))

In [ ]:
i = 0

while i <9:
    
    i = i +1
    if i == 5:
        continue #continue is used to skip the current iteration
        
    if i ==8:
        break
    print(f'value of i is {i}')
else:
    print("Loop is exited")

In [ ]:
0>10 #all relational operators have boolean output

### Functions

Python functions are defined using the `def` keyword. For example:

In [ ]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))

We will often define functions to take optional keyword arguments, like this:

In [ ]:
def hello(name, loud=False):
    if loud:
        print('HELLO, {}'.format(name.upper()))
    else:
        print('Hello, {}!'.format(name))

hello('Bob')
hello('Fred', loud=True)

In [ ]:
import this

OOPs --> Object oriented Programming

Everything in python is an object

In [ ]:
print(type(1))

In [ ]:
#blueprint --> (logical abstraction of a house)

In [ ]:
#class is the blueprint for it's object

### Classes

The syntax for defining classes in Python is straightforward:

In [ ]:
class Greeter:

    # Constructor --> is function that executed whenever an object of that class is created
    def __init__(self, name): # double underscore is called dundor 
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
          print('HELLO, {}'.format(self.name.upper()))
        else:
          print('Hello, {}!'.format(self.name))




In [ ]:
g = Greeter(eval(input("Enter the name")))  # Construct an instance of the Greeter class

In [ ]:
g.name

In [ ]:
g.greet(True)

In [ ]:
g.name = 'Pragyan'

In [ ]:
g.name

In [ ]:
g.

In [ ]:
g.age = 25

In [ ]:
g.age

In [ ]:
g.

In [ ]:
g1 = Greeter("Priyanka")

In [ ]:
g1.age

In [ ]:
g1.age =25

In [ ]:
g.greet()            # Call an instance method; prints "Hello, Fred"


In [ ]:
g.greet(loud=True)   # Call an instance method; prints "HELLO, FRED!"

In [ ]:
# The code below shows another example of inheritance
# Dog and Cat are two classes which inherits from Animal.
# This an instance created from Dog or Cat can access the methods
# in the Animal class, ie.. eat().

# The instance of 'Dog' can access the methods of the Dog class
# and it's parent class 'Animal'.

# The instance of 'Cat' can access the methods of the Cat class
# and it's parent class 'Animal'.

# But the instance created from 'Cat' cannot access the attributes
# within the 'Dog' class, and vice versa.


class Animal(object):
    def __init__(self, name):
        self.name = name

    def eat(self, food):
        print("%s is eating %s" % (self.name, food))


class Dog(Animal):
    def fetch(self, thing):
        print("{} goes after the {}" % (self.name, thing))


class Cat(Animal):
    def swatstring(self):
        print("%s shred the string!" % self.name)




In [ ]:
d = Dog("Tyson")
c = Cat("Coco")



In [ ]:
d.

In [ ]:
d.fetch("Ball")

In [ ]:
d.eat("Bones")

In [ ]:
d.fetch("paper")
d.eat("dog food")
print("--------")
c.eat("cat food")
c.swatstring()



In [ ]:
# The below methods would fail, since the instances doesn't have
# have access to the other class.

c.fetch("frizbee")
d.swatstring()

In [ ]:
c.swatstring()

In [ ]:
ls = list(range(1,25))

In [ ]:
count = 0
for i in ls:
    if i % 2 ==0:
        count = count +1
        

In [ ]:
count

In [ ]:
nums = [1,2,3]

In [ ]:
nums*5

In [ ]:
import numpy as np

In [ ]:
np.array(nums)*3 #vectorization

In [ ]:
s = list(range(1,889))

In [ ]:
count = 0 

for i in s:
    if i%2 ==0:
        count = count + 1

In [ ]:
count

In [ ]:
sum(np.array(s)%2) #no of odd elements

In [ ]:
len(s)- sum(np.array(s)%2) #no of even elements

## Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this [tutorial](http://wiki.scipy.org/NumPy_for_Matlab_Users) useful to get started with Numpy.

To use Numpy, we first need to import the `numpy` package:

In [2]:
import numpy as np

In [ ]:
ls = list(range(1,25))

In [ ]:
np.array(ls)

In [ ]:
np.array(ls)*2

In [ ]:
sum(np.array(ls)%2)

In [ ]:
len(np.array(ls))-sum(np.array(ls)%2)

### Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [3]:
a = np.array([1, 2, 3])  # Create a rank 1 array
                  

In [4]:
type(a)

numpy.ndarray

In [9]:
a[0:2]

array([1, 2])

In [10]:
a.shape

(3,)

In [8]:
a[2]

3

In [28]:
print(type(a), a.shape, a[0], a[1], a[2])


<class 'numpy.ndarray'> (3,) 1 2 3


In [29]:
a[0] = 5                 # Change an element of the array
print(a)

[5 2 3]


In [12]:
b = np.array([[1,2,3],[4,5,6]])

In [14]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
b.shape

(2, 3)

In [15]:
b[0]

array([1, 2, 3])

In [17]:
b[0][0]

1

In [26]:
b[0,0] # array[row,col]

1

In [18]:
b[0][1]

2

In [27]:
b[0,1]

2

In [19]:
b[0][2]

3

In [16]:
b[1]

array([4, 5, 6])

In [20]:
b[1][0]

4

In [21]:
b[1][1]

5

In [22]:
b[1][2]

6

In [32]:
b = np.array([[1,2,3],[4,5,6],[6,5,3]])   # Create a rank 2 array
print(b)

[[1 2 3]
 [4 5 6]
 [6 5 3]]


In [33]:
print(b.shape)

(3, 3)


In [25]:
print(b[0, 0], b[0, 1], b[1, 0])

1 2 4


Numpy also provides many functions to create arrays:

In [34]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]]


In [35]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

[[1. 1.]]


In [38]:
c = np.full((3,3), 4) # Create a constant array
print(c)

[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [40]:
d = np.eye(2,2)        # Create a 2x2 identity matrix
print(d)

[[1. 0.]
 [0. 1.]]


In [42]:
e = np.random.random((2,3)) # Create an array filled with random values
print(e)

[[0.04796223 0.83243084 0.62614917]
 [0.88000995 0.59229638 0.3899299 ]]


In [44]:
x = np.zeros((3,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [47]:
y = np.ones((1,3))
print(a)

[[0. 0.]
 [0. 0.]]


In [49]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [50]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
y = np.array([[10,11,12],[13,14,15],[16,17,18]])

In [52]:
y

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [53]:
x+y

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [54]:
x-y

array([[-9, -9, -9],
       [-9, -9, -9],
       [-9, -9, -9]])

In [55]:
x*y

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [56]:
x**y

array([[          1,        2048,      531441],
       [   67108864,  1808548329,  2033549312],
       [-1526366847,           0, -1953380655]], dtype=int32)

In [57]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
sum(x)#built in sum function does column wise sum

array([12, 15, 18])

In [62]:
np.sum(x)#total sum

45

In [63]:
np.sum(x,axis=0)#column wise sum

array([12, 15, 18])

In [64]:
np.sum(x,axis=1)#row wise sum

array([ 6, 15, 24])

In [65]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
x.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
a = np.array([1,2,3])

In [ ]:
b = np.array([2,3,5])

In [ ]:
np.setdiff1d(a,b)

In [ ]:
np.setdiff1d(b,a)

In [70]:
np.abs??

In [67]:
x = np.array([-1.2, 1.2])

In [68]:
np.abs(x)

array([1.2, 1.2])

In [ ]:
n

### Array indexing

Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [71]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
a.shape

(3, 4)

In [77]:
a[:2, 1:3]

array([[2, 3],
       [6, 7]])

In [76]:
a[0,2]

3

In [84]:
np.diff??

In [80]:
a = np.matrix('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

In [81]:
b = np.matrix('1 2; 3 4;5 6')

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [87]:
 c = np.matrix([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [96]:
c

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [97]:
c[::]

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [98]:
sum(c)

matrix([[15, 18, 21, 24]])

In [99]:
np.sum(c)

78

In [100]:
np.sum(c,axis=0)

matrix([[15, 18, 21, 24]])

In [101]:
np.sum(c,axis=1)

matrix([[10],
        [26],
        [42]])

In [103]:
c

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [107]:
c[1,2]

7

In [108]:
c[:2,1:3]

matrix([[2, 3],
        [6, 7]])

In [121]:
c.min()

1

In [122]:
c.max()

12

In [124]:
c.mean()

6.5

In [128]:
c.avg()

AttributeError: 'matrix' object has no attribute 'avg'

In [117]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [110]:
a.min()

1

In [111]:
a.max()

12

In [112]:
a.mean()

6.5

In [114]:
a.mean(axis=0)#column wise mean/average

array([5., 6., 7., 8.])

In [120]:
42/4

10.5

In [115]:
a.mean(axis=1) # row wise mean

array([ 2.5,  6.5, 10.5])

In [ ]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
b = a[:2, 1:3]
print(b)

In [ ]:
b

In [ ]:
b[0,0] = 77

In [ ]:
b

A slice of an array is a view into the same data, so modifying it will modify the original array.

In [ ]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1]) 

You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array.

In [2]:
import numpy as np

In [3]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
a.shape

(3, 4)

In [5]:
row_r1 = a[1, :] 

In [6]:
row_r1.shape

(4,)

In [7]:
row_r1

array([5, 6, 7, 8])

In [ ]:
a[[1,2]]

In [ ]:
row_r1

In [ ]:
row_r2 = a[1:2, :] 

In [ ]:
row_r2

In [ ]:
row_r2.shape

In [ ]:
row_r3 = a[[1], :] 

In [ ]:
row_r3

In [ ]:
row_r3.shape

Two ways of accessing the data in the middle row of the array.
Mixing integer indexing with slices yields an array of lower rank,
while using only slices yields an array of the same rank as the
original array:

In [8]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [11]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]


In [10]:
col_r1

array([ 2,  6, 10])

In [12]:
col_r1.shape

(3,)

In [ ]:
col_r2 = a[:, 1:2]


In [ ]:
col_r2

In [ ]:
col_r1.shape

In [ ]:
col_r2.shape

In [ ]:
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

In [ ]:
a

In [ ]:
a[:, 1]

In [ ]:
a[:, 1:2]

In [ ]:
a[:,[1]]

Integer array indexing: When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [ ]:
a = np.array([[1,2],
              [3, 4], 
              [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and 
print(a[[0, 1, 2], 
        [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print([a[0, 0], a[1, 1], a[2, 0]])

In [ ]:
a

In [ ]:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

In [ ]:
a

In [ ]:
a[[1,2]]

In [ ]:
a[1:3]

In [ ]:
a[[0,1,2],
  [0,1,0]]

In [ ]:
print(a[[0, 1, 2], [0, 1, 0]])

In [ ]:
a[1:3,]

In [ ]:
10/3

In [ ]:
import  math as m

In [ ]:
m.

In [ ]:
math.isclose()

In [ ]:
a = 0.1 + 0.1 +0.1

In [ ]:
b = 0.3

In [ ]:
a == b

In [ ]:
m

In [ ]:
a

In [ ]:
b

In [ ]:
x = 10

In [ ]:
y = 10

In [ ]:
x ==y

In [ ]:
x is y

In [ ]:
p =555

In [ ]:
q = 555

In [ ]:
p == q

In [ ]:
p is q

In [ ]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [ ]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

In [ ]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

In [ ]:
b

In [ ]:
a[[0,1,2,3],b]

In [ ]:


# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

In [ ]:
a

In [ ]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])


In [ ]:
a

In [ ]:
a[a >2]

In [ ]:

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.



In [ ]:
print(bool_idx)

In [ ]:
a[bool_idx]

In [ ]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 2])

For brevity we have left out a lot of details about numpy array indexing; if you want to know more you should read the documentation.

### Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

### Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

In [ ]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

In [ ]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

Note that unlike MATLAB, `*` is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

You can also use the `@` operator which is equivalent to numpy's `dot` operator.

In [ ]:
print(v @ w)

In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

In [ ]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [ ]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

In [ ]:
x

You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [ ]:
print(x)
print("transpose\n", x.T)

In [ ]:
v = np.array([[1,2,3]])
print(v )
print("transpose\n", v.T)

### Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

In [ ]:
x

In [ ]:
v

In [ ]:
y = np.empty_like(x)   # Create an empty matrix with the same shape as x
y

In [ ]:
# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

This works; however when the matrix `x` is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix `x` is equivalent to forming a matrix `vv` by stacking multiple copies of `v` vertically, then performing elementwise summation of `x` and `vv`. We could implement this approach like this:

In [ ]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)                # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

In [ ]:
y = x + vv  # Add x and vv elementwise
print(y)

Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

If this explanation does not make sense, try reading the explanation from the [documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) or this [explanation](http://wiki.scipy.org/EricsBroadcastingDoc).

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the [documentation](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Here are some applications of broadcasting:

In [ ]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)

In [ ]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)

In [ ]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:

print((x.T + w).T)

In [ ]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

In [ ]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x * 2)

Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the [numpy reference](http://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.

## Matplotlib

Matplotlib is a plotting library. In this section give a brief introduction to the `matplotlib.pyplot` module, which provides a plotting system similar to that of MATLAB.

In [ ]:
import matplotlib.pyplot as plt

By running this special iPython command, we will be displaying plots inline:

In [ ]:
%matplotlib inline

### Plotting

The most important function in `matplotlib` is plot, which allows you to plot 2D data. Here is a simple example:

In [ ]:
# Compute the x and y coordinates for points on a sine curve
x = np.arange(0, 3 * np.pi, 0.1)
y = np.sin(x)

# Plot the points using matplotlib
plt.plot(x, y)

With just a little bit of extra work we can easily plot multiple lines at once, and add a title, legend, and axis labels:

In [ ]:
y_sin = np.sin(x)
y_cos = np.cos(x)

# Plot the points using matplotlib
plt.plot(x, y_sin)
plt.plot(x, y_cos)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine'])

### Subplots 

You can plot different things in the same figure using the subplot function. Here is an example:

In [ ]:
# Compute the x and y coordinates for points on sine and cosine curves
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# Set up a subplot grid that has height 2 and width 1,
# and set the first such subplot as active.
plt.subplot(2, 1, 1)

# Make the first plot
plt.plot(x, y_sin)
plt.title('Sine')

# Set the second subplot as active, and make the second plot.
plt.subplot(2, 1, 2)
plt.plot(x, y_cos)
plt.title('Cosine')

# Show the figure.
plt.show()

You can read much more about the `subplot` function in the [documentation](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.subplot).

In [ ]:
class Dog:
    species = "Canis familiaris"

    def __init__(self, name, age):
        self.name = name
        self.age = age

    def __str__(self):
        return f"{self.name} is {self.age} years old"

    def speak(self, sound):
        return f"{self.name} says {sound}"

In [ ]:
class JackRussellTerrier(Dog):
    pass

class Dachshund(Dog):
    pass

class Bulldog(Dog):
    pass

In [ ]:
dog1 = JackRussellTerrier("Maggi",7)

In [ ]:
dog1.name

In [ ]:
dog1.age

In [ ]:
dog1

In [ ]:
dog1.speak("WOW WOW")

In [ ]:
dog1.species

In [ ]:
import pandas as pd

In [ ]:
area = pd.Series({'California': 2, 'Texas': 3,
                  'New York': 4, 'Florida': 5,
                  'Illinois': 6})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

In [ ]:
data['SQ_Area'] = data['area'].apply(lambda x : x**2)

In [ ]:
data.apply??

In [ ]:
x = lambda a : a + 10

In [ ]:
x(6)

In [ ]:
import math as m

In [ ]:
dir(m)

In [ ]:
import pandas as pd

In [ ]:
dir(pd)

In [ ]:
data = [
    {"id": 1, "name": {"first": "Coleen", "last": "Volk"}},
    {"name": {"given": "Mark", "family": "Regner"}},
    {"id": 2, "name": "Faye Raker"},
]

In [ ]:
pd.json_normalize(data)

In [ ]:
data = [
    {
        "id": 1,
        "name": "Cole Volk",
        "fitness": {"height": 130, "weight": 60},
    },
    {"name": "Mark Reg", "fitness": {"height": 130, "weight": 60}},
    {
        "id": 2,
        "name": "Faye Raker",
        "fitness": {"height": 130, "weight": 60},
    },
]

In [ ]:
pd.json_normalize(data, max_level=0)

In [ ]:
pd.json_normalize(data)

In [ ]:
data = [
    {
        "id": 1,
        "name": "Cole Volk",
        "fitness": {"height": 130, "weight": 60},
    },
    {"name": "Mark Reg", "fitness": {"height": 130, "weight": 60}},
    {
        "id": 2,
        "name": "Faye Raker",
        "fitness": {"height": 130, "weight": 60},
    },
]

In [ ]:
pd.json_normalize(data, max_level=1)

In [ ]:
data = [
    {
        "state": "Florida",
        "shortname": "FL",
        "info": {"governor": "Rick Scott"},
        "counties": [
            {"name": "Dade", "population": 12345},
            {"name": "Broward", "population": 40000},
            {"name": "Palm Beach", "population": 60000},
        ],
    },
    {
        "state": "Ohio",
        "shortname": "OH",
        "info": {"governor": "John Kasich"},
        "counties": [
            {"name": "Summit", "population": 1234},
            {"name": "Cuyahoga", "population": 1337},
        ],
    },
]

In [ ]:
pd.json_normalize(
    data, "counties", ["state", "shortname", ["info", "governor"]]
)

In [ ]:
result

In [ ]:
result = pd.json_normalize(data,max_level=2)

In [ ]:
result

In [ ]:
data = {"A": [1, 2]}


In [ ]:
pd.json_normalize(data, "A", record_prefix="Prefix.")

In [ ]:
df = pd.DataFrame({'A': {0: 'a', 1: 'b', 2: 'c'},
                   'B': {0: 1, 1: 3, 2: 5},
                   'C': {0: 2, 1: 4, 2: 6}})

In [ ]:
df

In [ ]:
pd.melt(df, id_vars=['A'], value_vars=['B'])

In [ ]:
pd.melt(df, id_vars=['A'], value_vars=['B', 'C'])

In [ ]:
# pd.melt(df, id_vars=['A'], value_vars=['B'],
#         var_name='myVarname', value_name='myValname')

In [ ]:
pd.melt(df, id_vars=['A'], value_vars=['B', 'C'], ignore_index=False)

In [ ]:
df.columns = [list('ABC'), list('DEF')]

In [ ]:
df

In [ ]:
pd.melt(df, col_level=0, id_vars=['A'], value_vars=['B'])

In [ ]:
pd.melt(df, id_vars=[('A', 'D')], value_vars=[('B', 'E')])